// Vocabulary compiled from uploaded sheets:
// Set A: Technical Term Vocabulary for HIT.1 & HIT (Premium)
// Set B: General Term Vocabulary T.Ryan (Lessons 1-5)

const VOCAB_SETS = {
  "IT & Technical Terms": [
    { en: "Information Technology", th: "เทคโนโลยีสารสนเทศ" },
    { en: "Artificial Intelligence", th: "ปัญญาประดิษฐ์" },
    { en: "Computer", th: "คอมพิวเตอร์" },
    { en: "Laptop", th: "คอมพิวเตอร์พกพา" },
    { en: "Desktop", th: "คอมพิวเตอร์ตั้งโต๊ะ" },
    { en: "Hardware", th: "อุปกรณ์คอมพิวเตอร์" },
    { en: "Software", th: "โปรแกรมคอมพิวเตอร์" },
    { en: "Operating System", th: "ระบบปฏิบัติการ" },
    { en: "Windows", th: "ระบบปฏิบัติการวินโดวส์" },
    { en: "macOS", th: "ระบบปฏิบัติการแมค" },
    { en: "Linux", th: "ระบบปฏิบัติการลินุกซ์" },
    { en: "Application", th: "โปรแกรมประยุกต์" },
    { en: "Program", th: "โปรแกรม" },
    { en: "File", th: "แฟ้มข้อมูล" },
    { en: "Folder", th: "โฟลเดอร์" },
    { en: "Database", th: "ฐานข้อมูล" },
    { en: "Server", th: "เครื่องแม่ข่าย" },
    { en: "Client", th: "เครื่องลูกข่าย" },
    { en: "Network", th: "เครือข่าย" },
    { en: "Internet", th: "อินเทอร์เน็ต" },
    { en: "Website", th: "เว็บไซต์" },
    { en: "Web Browser", th: "โปรแกรมท่องเว็บ" },
    { en: "Search Engine", th: "เครื่องมือค้นหา" },
    { en: "URL", th: "ที่อยู่เว็บไซต์" },
    { en: "Domain Name", th: "ชื่อโดเมน" },
    { en: "Cloud Computing", th: "การประมวลผลบนคลาวด์" },
    { en: "Cloud Storage", th: "ที่เก็บข้อมูลบนคลาวด์" },
    { en: "Google Drive", th: "กูเกิลไดรฟ์" },
    { en: "OneDrive", th: "วันไดรฟ์" },
    { en: "Backup", th: "สำรองข้อมูล" },
    { en: "Programming", th: "การเขียนโปรแกรม" },
    { en: "Coding", th: "การเขียนโค้ด" },
    { en: "Source Code", th: "รหัสต้นฉบับ" },
    { en: "Algorithm", th: "ขั้นตอนการแก้ปัญหา" },
    { en: "Flowchart", th: "ผังงาน" },
    { en: "Function", th: "ฟังก์ชัน" },
    { en: "Variable", th: "ตัวแปร" },
    { en: "Data Type", th: "ชนิดข้อมูล" },
    { en: "Debugging", th: "การแก้ไขข้อผิดพลาด" },
    { en: "Syntax Error", th: "ข้อผิดพลาดทางไวยากรณ์" },
    { en: "Python", th: "ภาษาไพธอน" },
    { en: "Java", th: "ภาษาจาวา" },
    { en: "JavaScript", th: "ภาษาจาวาสคริปต์" },
    { en: "HTML", th: "ภาษาสร้างเว็บ" },
    { en: "CSS", th: "ภาษาตกแต่งเว็บ" },
    { en: "SQL", th: "ภาษาจัดการฐานข้อมูล" },
    { en: "Mobile App", th: "แอปพลิเคชันมือถือ" },
    { en: "Web Application", th: "เว็บแอปพลิเคชัน" },
    { en: "User Interface", th: "ส่วนติดต่อผู้ใช้" },
    { en: "User Experience", th: "ประสบการณ์ผู้ใช้" }
  ],

  "Lesson 1: Self-Introduction": [
    { en: "Name", th: "ชื่อ" },
    { en: "Introduce", th: "แนะนำ" },
    { en: "Nickname", th: "ชื่อเล่น" },
    { en: "Age", th: "อายุ" },
    { en: "Old", th: "แก่ / อายุ" },
    { en: "From", th: "มาจาก" },
    { en: "Live", th: "อาศัยอยู่" },
    { en: "Address", th: "ที่อยู่" },
    { en: "Phone number", th: "เบอร์โทรศัพท์" },
    { en: "Email", th: "อีเมล" },
    { en: "Job", th: "อาชีพ" },
    { en: "Occupation", th: "อาชีพ" },
    { en: "Student", th: "นักเรียน" },
    { en: "Hobby", th: "งานอดิเรก" },
    { en: "Like", th: "ชอบ" },
    { en: "Favorite", th: "ที่ชื่นชอบ" },
    { en: "Family", th: "ครอบครัว" },
    { en: "Graduate", th: "สำเร็จการศึกษา" },
    { en: "Experience", th: "ประสบการณ์" },
    { en: "Goal", th: "เป้าหมาย" }
  ],

  "Lesson 2: Asking-Giving Directions": [
    { en: "Direction", th: "ทิศทาง" },
    { en: "Turn", th: "เลี้ยว" },
    { en: "Left", th: "ซ้าย" },
    { en: "Right", th: "ขวา" },
    { en: "Straight", th: "ตรง" },
    { en: "Intersection", th: "สี่แยก" },
    { en: "Corner", th: "หัวมุม" },
    { en: "Traffic light", th: "ไฟจราจร" },
    { en: "Crosswalk", th: "ทางม้าลาย" },
    { en: "Opposite", th: "ตรงข้าม" },
    { en: "Next to", th: "ถัดจาก" },
    { en: "Near", th: "ใกล้" },
    { en: "Far", th: "ไกล" },
    { en: "Behind", th: "ด้านหลัง" },
    { en: "In front of", th: "ด้านหน้า" },
    { en: "Map", th: "แผนที่" },
    { en: "Block", th: "ช่วงตึก" },
    { en: "Avenue", th: "ถนนใหญ่" },
    { en: "Bridge", th: "สะพาน" },
    { en: "Destination", th: "จุดหมาย" }
  ],

  "Lesson 3: Shopping": [
    { en: "Buy", th: "ซื้อ" },
    { en: "Sell", th: "ขาย" },
    { en: "Price", th: "ราคา" },
    { en: "Cost", th: "ราคา/ต้นทุน" },
    { en: "Discount", th: "ส่วนลด" },
    { en: "Cash", th: "เงินสด" },
    { en: "Credit card", th: "บัตรเครดิต" },
    { en: "Receipt", th: "ใบเสร็จ" },
    { en: "Change", th: "เงินทอน" },
    { en: "Expensive", th: "แพง" },
    { en: "Cheap", th: "ถูก" },
    { en: "Size", th: "ขนาด" },
    { en: "Try on", th: "ลองสวม" },
    { en: "Refund", th: "คืนเงิน" },
    { en: "Exchange", th: "แลกเปลี่ยน" },
    { en: "Customer", th: "ลูกค้า" },
    { en: "Cashier", th: "พนักงานคิดเงิน" },
    { en: "Total", th: "ยอดรวม" },
    { en: "Sale", th: "การลดราคา" },
    { en: "Product", th: "สินค้า" }
  ],

  "Lesson 4: Restaurant": [
    { en: "Reservation", th: "การจอง" },
    { en: "Table", th: "โต๊ะ" },
    { en: "Menu", th: "เมนู" },
    { en: "Order", th: "สั่งอาหาร" },
    { en: "Waiter", th: "พนักงานเสิร์ฟชาย" },
    { en: "Waitress", th: "พนักงานเสิร์ฟหญิง" },
    { en: "Appetizer", th: "อาหารเรียกน้ำย่อย" },
    { en: "Main course", th: "อาหารจานหลัก" },
    { en: "Dessert", th: "ของหวาน" },
    { en: "Beverage", th: "เครื่องดื่ม" },
    { en: "Bill", th: "ใบเสร็จ" },
    { en: "Tip", th: "เงินทิป" },
    { en: "Recommend", th: "แนะนำ" },
    { en: "Delicious", th: "อร่อย" },
    { en: "Spicy", th: "เผ็ด" },
    { en: "Medium", th: "ปานกลาง" },
    { en: "Well-done", th: "สุกมาก" },
    { en: "Check", th: "ใบเรียกเก็บเงิน" },
    { en: "Pay", th: "จ่ายเงิน" },
    { en: "Receipt", th: "ใบเสร็จ" }
  ],

  "Lesson 5: Hotel": [
    { en: "Reservation", th: "การจอง" },
    { en: "Check-in", th: "การเข้าพัก" },
    { en: "Receptionist", th: "พนักงานต้อนรับ" },
    { en: "Passport", th: "หนังสือเดินทาง" },
    { en: "ID card", th: "บัตรประชาชน" },
    { en: "Single room", th: "ห้องเดี่ยว" },
    { en: "Double room", th: "ห้องคู่" },
    { en: "Key card", th: "คีย์การ์ด" },
    { en: "Lobby", th: "ล็อบบี้" },
    { en: "Elevator", th: "ลิฟต์" },
    { en: "Luggage", th: "กระเป๋าเดินทาง" },
    { en: "Bellboy", th: "พนักงานยกกระเป๋า" },
    { en: "Deposit", th: "เงินมัดจำ" },
    { en: "Checkout", th: "การคืนห้อง" },
    { en: "Facilities", th: "สิ่งอำนวยความสะดวก" },
    { en: "Breakfast", th: "อาหารเช้า" },
    { en: "Complimentary", th: "ฟรี" },
    { en: "Available", th: "ว่าง" },
    { en: "Confirm", th: "ยืนยัน" },
    { en: "Signature", th: "ลายเซ็น" }
  ]
};
